version: '3.8'

services:
  # Removed postgres service
  # Removed pgadmin service

  backend:
    container_name: backend-service
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      # - SECRET_KEY=your-secret-key-for-development # Likely no longer needed
      - GOOGLE_APPLICATION_CREDENTIALS=/app/serviceAccountKey.json # Ensure serviceAccountKey.json is in backend/
      # - GEMINI_API_KEY=your_actual_gemini_api_key_here # Set your Gemini API Key here or use an .env file
    # depends_on: # Removed postgres dependency
    #  - postgres

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
