
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - SECRET_KEY=your-secret-key-for-development
      # Add your Gemini API key here or use an .env file
      # - GEMINI_API_KEY=your-gemini-api-key

  frontend:
    # This would be your frontend service
    # For development, you might run this separately
    image: node:16
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: sh -c "echo 'Frontend service placeholder - in development you would run this separately'"
