
version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medical_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - SECRET_KEY=your-secret-key-for-development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/medical_app
      # Add your Gemini API key here or use an .env file
      # - GEMINI_API_KEY=your-gemini-api-key
    depends_on:
      - postgres

  frontend:
    # This would be your frontend service
    # For development, you might run this separately
    image: node:16
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: sh -c "echo 'Frontend service placeholder - in development you would run this separately'"

volumes:
  postgres_data:
