// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxnwcozjseafjlglmzii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4bndjb3pqc2VhZmpsZ2xtemlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTkyOTgsImV4cCI6MjA2MTMzNTI5OH0.eHokIIsnScuBTpBNgHefPMg5rTYDntXDKGcOYELlQek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);